<a href="https://colab.research.google.com/github/krittikaroy0/CSE366_AI/blob/main/CSE366_project_sec1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Krittika Roy 

ID: 2020-1-60-065

**naive bayesian**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set(style="darkgrid")
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

In [ ]:
# Load the bank dataset
bank_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/train_bank.csv')

In [ ]:
# Separate the features (X) and the target variable (y)
X = bank_data.drop('deposit', axis=1)
y = bank_data['deposit']

In [ ]:
# Perform train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Print the shapes of the train and test sets
print("Training set shape:", X_train.shape, y_train.shape)
print("Test set shape:", X_test.shape, y_test.shape)

Training set shape: (8930, 16) (8930,)
Test set shape: (2233, 16) (2233,)

In [ ]:
display('Bank Train Data:',X.head(), 'Bank Test Data:',y.head())

'Bank Train Data:'

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
0,59.0,admin.,married,secondary,no,2343.0,yes,no,unknown,5.0,may,1042.0,1.0,-1.0,0.0,unknown
1,56.0,admin.,married,secondary,no,45.0,no,no,unknown,5.0,may,1467.0,1.0,-1.0,0.0,unknown
2,41.0,technician,married,secondary,no,1270.0,yes,no,unknown,5.0,may,1389.0,1.0,-1.0,0.0,unknown
3,55.0,services,married,secondary,no,2476.0,yes,no,unknown,5.0,may,579.0,1.0,-1.0,0.0,unknown
4,54.0,admin.,married,tertiary,no,184.0,no,no,unknown,5.0,may,673.0,2.0,-1.0,0.0,unknown

'Bank Test Data:'

0    yes
1    yes
2    yes
3    yes
4    yes
Name: deposit, dtype: object

In [ ]:
X.describe()

,age,balance,day,duration,campaign,pdays,previous
count,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000
mean,41.231948,1528.538524,15.658036,371.993818,2.508421,51.330407,0.832557
std,11.913369,3225.413326,8.420740,347.128386,2.722077,108.758282,2.292007
min,18.000000,-6847.000000,1.000000,2.000000,1.000000,-1.000000,0.000000
25%,32.000000,122.000000,8.000000,138.000000,1.000000,-1.000000,0.000000
50%,39.000000,550.000000,15.000000,255.000000,2.000000,-1.000000,0.000000
75%,49.000000,1708.000000,22.000000,496.000000,3.000000,20.750000,1.000000
max,95.000000,81204.000000,31.000000,3881.000000,63.000000,854.000000,58.000000

In [ ]:
print(bank_data.columns)

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'deposit'],
      dtype='object')

In [ ]:
bank_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11163 entries, 0 to 11162
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        11162 non-null  float64
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  float64
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  float64
 10  month      11162 non-null  object
 11  duration   11162 non-null  float64
 12  campaign   11162 non-null  float64
 13  pdays      11162 non-null  float64
 14  previous   11162 non-null  float64
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: float64(7), object(10)
memory usage: 1.4+ MB

In [ ]:
bank_data.corr()

<ipython-input-67-e23b2d98f117>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  bank_data.corr()

               age   balance       day  duration  campaign     pdays  previous
age       1.000000  0.112300 -0.000762  0.000189 -0.005278  0.002774  0.020169
balance   0.112300  1.000000  0.010467  0.022436 -0.013894  0.017411  0.030805
day      -0.000762  0.010467  1.000000 -0.018511  0.137007 -0.077232 -0.058981
duration  0.000189  0.022436 -0.018511  1.000000 -0.041557 -0.027392 -0.026716
campaign -0.005278 -0.013894  0.137007 -0.041557  1.000000 -0.102726 -0.049699
pdays     0.002774  0.017411 -0.077232 -0.027392 -0.102726  1.000000  0.507272
previous  0.020169  0.030805 -0.058981 -0.026716 -0.049699  0.507272  1.000000

In [ ]:
bank_data.describe()

,age,balance,day,duration,campaign,pdays,previous
count,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000,11162.000000
mean,41.231948,1528.538524,15.658036,371.993818,2.508421,51.330407,0.832557
std,11.913369,3225.413326,8.420740,347.128386,2.722077,108.758282,2.292007
min,18.000000,-6847.000000,1.000000,2.000000,1.000000,-1.000000,0.000000
25%,32.000000,122.000000,8.000000,138.000000,1.000000,-1.000000,0.000000
50%,39.000000,550.000000,15.000000,255.000000,2.000000,-1.000000,0.000000
75%,49.000000,1708.000000,22.000000,496.000000,3.000000,20.750000,1.000000
max,95.000000,81204.000000,31.000000,3881.000000,63.000000,854.000000,58.000000

In [ ]:
print('Total cells:', X.size)
print('Total cells:', y.size)

Total cells: 178608
Total cells: 11163

In [ ]:
X.iloc[0,0]

59.0

In [ ]:
X.iloc[59]

age                57.0
job          technician
marital         married
education      tertiary
default              no
balance            -1.0
housing              no
loan                 no
contact         unknown
day                14.0
month               may
duration          850.0
campaign            2.0
pdays              -1.0
previous            0.0
poutcome        unknown
Name: 59, dtype: object

In [ ]:
X.iloc[[59]]

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
59,57.0,technician,married,tertiary,no,-1.0,no,no,unknown,14.0,may,850.0,2.0,-1.0,0.0,unknown

In [ ]:
X[['job','education','marital']]

              job  education  marital
0          admin.  secondary  married
1          admin.  secondary  married
2      technician  secondary  married
3        services  secondary  married
4          admin.   tertiary  married
...           ...        ...      ...
11158    services  secondary  married
11159  technician  secondary   single
11160  technician  secondary  married
11161  technician  secondary  married
11162         NaN        NaN      NaN

[11163 rows x 3 columns]

In [ ]:
X.dropna( inplace = True)

In [ ]:
X

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome
0,59.0,admin.,married,secondary,no,2343.0,yes,no,unknown,5.0,may,1042.0,1.0,-1.0,0.0,unknown
1,56.0,admin.,married,secondary,no,45.0,no,no,unknown,5.0,may,1467.0,1.0,-1.0,0.0,unknown
2,41.0,technician,married,secondary,no,1270.0,yes,no,unknown,5.0,may,1389.0,1.0,-1.0,0.0,unknown
3,55.0,services,married,secondary,no,2476.0,yes,no,unknown,5.0,may,579.0,1.0,-1.0,0.0,unknown
4,54.0,admin.,married,tertiary,no,184.0,no,no,unknown,5.0,may,673.0,2.0,-1.0,0.0,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11157,33.0,blue-collar,single,primary,no,1.0,yes,no,cellular,20.0,apr,257.0,1.0,-1.0,0.0,unknown
11158,39.0,services,married,secondary,no,733.0,no,no,unknown,16.0,jun,83.0,4.0,-1.0,0.0,unknown
11159,32.0,technician,single,secondary,no,29.0,no,no,cellular,19.0,aug,156.0,2.0,-1.0,0.0,unknown
11160,43.0,technician,married,secondary,no,0.0,no,yes,cellular,8.0,may,9.0,2.0,172.0,5.0,failure
11161,34.0,technician,married,secondary,no,0.0,no,no,cellular,9.0,jul,628.0,1.0,-1.0,0.0,unknown

In [ ]:
y.dropna( inplace = True)

In [ ]:
y

0        yes
1        yes
2        yes
3        yes
4        yes
        ...
11157     no
11158     no
11159     no
11160     no
11161     no
Name: deposit, Length: 11162, dtype: object

In [ ]:
y.value_counts()

no     5873
yes    5289
Name: deposit, dtype: int64

In [ ]:
bank_data.isnull().sum()

age          1
job          1
marital      1
education    1
default      1
balance      1
housing      1
loan         1
contact      1
day          1
month        1
duration     1
campaign     1
pdays        1
previous     1
poutcome     1
deposit      1
dtype: int64

In [ ]:
bank_data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
11158    False
11159    False
11160    False
11161    False
11162    False
Length: 11163, dtype: bool

In [ ]:
duplicates_bank_data = bank_data[bank_data.duplicated()]
print(duplicates_bank_data)

Empty DataFrame
Columns: [age, job, marital, education, default, balance, housing, loan, contact, day, month, duration, campaign, pdays, previous, poutcome, deposit]
Index: []

In [ ]:
age = input("Enter Your Age")
denumerator =bank_data[ (bank_data["marital"] == "married" ) & (bank_data['age'] == age ) ].count()
print(denumerator)

Enter Your Age56
age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [ ]:
 bank_data["job"]

0            admin.
1            admin.
2        technician
3          services
4            admin.
            ...
11158      services
11159    technician
11160    technician
11161    technician
11162           NaN
Name: job, Length: 11163, dtype: object

In [ ]:
total_count = bank_data.count()[0]

df_student =bank_data[ bank_data["job"] == "student" ]
total_student_count = df_student.count()[0]
print("Total student:",total_student_count)
prior = total_student_count/total_count 
print("prior",prior )

df_student_non_deposit =bank_data [ (bank_data["job"] == "student") & (bank_data["deposit"] == 'no') ]
student_non_deposit_count = df_student_non_deposit.count()[0]
print("Total student_non_deposit:",student_non_deposit_count)
likelihood = student_non_deposit_count / (total_student_count)
print("likelihood:" ,likelihood) 

df_non_deposit =bank_data[bank_data["deposit"] == "no"]
total_non_deposit_count = df_non_deposit.count()[0]
print("Total non deposit:",total_non_deposit_count)
Evidence =  total_non_deposit_count/total_count
print("Evidence:",Evidence )

Prosterior =  (likelihood*prior)/Evidence
print("Prosterior:",Prosterior )

Total student: 360
prior 0.03225228453682136
Total student_non_deposit: 91
likelihood: 0.25277777777777777
Total non deposit: 5873
Evidence: 0.5261601863465328
Prosterior: 0.015494636471990465

In [ ]:
total_count = bank_data.count()[0]

df_student =bank_data[ bank_data["job"] == "student" ]
total_student_count = df_student.count()[0]
print("Total student:",total_student_count)
prior = total_student_count/total_count 
print("prior",prior )

df_student_deposit =bank_data [ (bank_data["job"] == "student") & (bank_data["deposit"] == 'yes') ]
student_deposit_count = df_student_deposit.count()[0]
print("Total student_deposit:",student_deposit_count)
likelihood = student_deposit_count / (total_student_count)
print("likelihood:" ,likelihood) 

df_deposit =bank_data[bank_data["deposit"] == "yes"]
total_deposit_count = df_deposit.count()[0]
print("Total deposit:",total_deposit_count)
Evidence =  total_deposit_count/total_count
print("Evidence:",Evidence )

Prosterior =  (likelihood*prior)/Evidence
print("Prosterior:",Prosterior )

Total student: 360
prior 0.03225228453682136
Total student_deposit: 269
likelihood: 0.7472222222222222
Total deposit: 5289
Evidence: 0.4738398136534671
Prosterior: 0.050860276044620914

In [ ]:
total_count = bank_data.count()[0]

df_admin =bank_data[ bank_data["job"] == "admin." ]
total_admin_count = df_admin.count()[0]
print("Total admin:",total_admin_count)
prior = total_admin_count/total_count 
print("prior",prior )

df_admin_non_deposit =bank_data [ (bank_data["job"] == "admin.") & (bank_data["deposit"] == 'no') ]
admin_non_deposit_count = df_admin_non_deposit.count()[0]
print("Total admin_non_deposit:",admin_non_deposit_count)
likelihood = admin_non_deposit_count / (total_admin_count)
print("likelihood:" ,likelihood) 

df_non_deposit =bank_data[bank_data["deposit"] == "no"]
total_non_deposit_count = df_non_deposit.count()[0]
print("Total non deposit:",total_non_deposit_count)
Evidence =  total_non_deposit_count/total_count
print("Evidence:",Evidence )

Prosterior =  (likelihood*prior)/Evidence
print("Prosterior:",Prosterior )

Total admin: 1334
prior 0.11951263214477692
Total admin_non_deposit: 703
likelihood: 0.5269865067466267
Total non deposit: 5873
Evidence: 0.5261601863465328
Prosterior: 0.1197003235143879

In [ ]:
total_count = bank_data.count()[0]

df_admin =bank_data[ bank_data["job"] == "admin." ]
total_admin_count = df_admin.count()[0]
print("Total admin:",total_admin_count)
prior = total_admin_count/total_count 
print("prior",prior )

df_admin_deposit =bank_data [ (bank_data["job"] == "admin.") & (bank_data["deposit"] == 'yes') ]
admin_deposit_count = df_admin_deposit.count()[0]
print("Total admin_deposit:",admin_deposit_count)
likelihood = admin_deposit_count / (total_admin_count)
print("likelihood:" ,likelihood) 

df_deposit =bank_data[bank_data["deposit"] == "yes"]
total_deposit_count = df_deposit.count()[0]
print("Total deposit:",total_deposit_count)
Evidence =  total_deposit_count/total_count
print("Evidence:",Evidence )

Prosterior =  (likelihood*prior)/Evidence
print("Prosterior:",Prosterior )

Total admin: 1334
prior 0.11951263214477692
Total admin_deposit: 631
likelihood: 0.47301349325337333
Total deposit: 5289
Evidence: 0.4738398136534671
Prosterior: 0.11930421629797693

In [ ]:
 bank_data["age"]

0        59.0
1        56.0
2        41.0
3        55.0
4        54.0
         ...
11158    39.0
11159    32.0
11160    43.0
11161    34.0
11162     NaN
Name: age, Length: 11163, dtype: float64

In [ ]:
total_count = bank_data.count()[0]
age = int(input("Enter Your Age: "))
df_age = bank_data[bank_data["age"] == age]
total_age_count = df_age.count()[0]
print("Total age:", total_age_count)

prior = total_age_count / total_count
print("prior:", prior)

df_age_deposit = bank_data[(bank_data["age"] == age) & (bank_data["deposit"] == 'yes')]
age_deposit_count = df_age_deposit.count()[0]
print("Total age_deposit:", age_deposit_count)

likelihood = age_deposit_count / total_age_count
print("likelihood:", likelihood)

df_deposit = bank_data[bank_data["deposit"] == "yes"]
total_deposit_count = df_deposit.count()[0]
print("Total deposit:", total_deposit_count)

Evidence = total_deposit_count / total_count
print("Evidence:", Evidence)

Posterior = (likelihood * prior) / Evidence
print("Posterior:", Posterior)

Enter Your Age: 56
Total age: 177
prior: 0.015857373230603836
Total age_deposit: 68
likelihood: 0.384180790960452
Total deposit: 5289
Evidence: 0.4738398136534671
Posterior: 0.012856872754774061

In [ ]:
total_count = bank_data.count()[0]
age = int(input("Enter Your Age: "))
df_age = bank_data[bank_data["age"] == age]
total_age_count = df_age.count()[0]
print("Total age:", total_age_count)

prior = total_age_count / total_count
print("prior:", prior)

df_age_non_deposit = bank_data[(bank_data["age"] == age) & (bank_data["deposit"] == 'no')]
age_non_deposit_count = df_age_non_deposit.count()[0]
print("Total age_non_deposit:", age_non_deposit_count)

likelihood = age_non_deposit_count / total_age_count
print("likelihood:", likelihood)

df_non_deposit = bank_data[bank_data["deposit"] == "no"]
total_non_deposit_count = df_non_deposit.count()[0]
print("Total non deposit:", total_non_deposit_count)

Evidence = total_non_deposit_count / total_count
print("Evidence:", Evidence)

Posterior = (likelihood * prior) / Evidence
print("Posterior:", Posterior)

Enter Your Age: 56
Total age: 177
prior: 0.015857373230603836
Total age_non_deposit: 109
likelihood: 0.615819209039548
Total non deposit: 5873
Evidence: 0.5261601863465328
Posterior: 0.01855950962029627

In [ ]:
 bank_data["marital"]

0        married
1        married
2        married
3        married
4        married
          ...
11158    married
11159     single
11160    married
11161    married
11162        NaN
Name: marital, Length: 11163, dtype: object

In [ ]:
total_count = bank_data.count()[0]

df_married =bank_data[ bank_data["marital"] == "married" ]
total_married_count = df_married.count()[0]
print("Total married:",total_married_count)
prior = total_married_count/total_count 
print("prior",prior )

df_married_non_deposit =bank_data [ (bank_data["marital"] == "married") & (bank_data["deposit"] == 'no') ]
married_non_deposit_count = df_married_non_deposit.count()[0]
print("Total married_non_deposit:",married_non_deposit_count)
likelihood = married_non_deposit_count / (total_married_count)
print("likelihood:" ,likelihood) 

df_non_deposit =bank_data[bank_data["deposit"] == "no"]
total_non_deposit_count = df_non_deposit.count()[0]
print("Total non deposit:",total_non_deposit_count)
Evidence =  total_non_deposit_count/total_count
print("Evidence:",Evidence )

Prosterior = (likelihood*prior)/Evidence
print("Prosterior:",Prosterior )

Total married: 6351
prior 0.5689840530370901
Total married_non_deposit: 3596
likelihood: 0.5662100456621004
Total non deposit: 5873
Evidence: 0.5261601863465328
Prosterior: 0.6122935467393155

In [ ]:
total_count = bank_data.count()[0]

df_married =bank_data[ bank_data["marital"] == "married" ]
total_married_count = df_married.count()[0]
print("Total married:",total_married_count)
prior = total_married_count/total_count 
print("prior",prior )

df_married_deposit =bank_data [ (bank_data["marital"] == "married") & (bank_data["deposit"] == 'yes') ]
married_deposit_count = df_married_deposit.count()[0]
print("Total married_deposit:",married_deposit_count)
likelihood = married_deposit_count / (total_married_count)
print("likelihood:" ,likelihood) 

df_deposit =bank_data[bank_data["deposit"] == "yes"]
total_deposit_count = df_deposit.count()[0]
print("Total deposit:",total_deposit_count)
Evidence =  total_deposit_count/total_count
print("Evidence:",Evidence )

Prosterior =  (likelihood*prior)/Evidence
print("Prosterior:",Prosterior )

Total married: 6351
prior 0.5689840530370901
Total married_deposit: 2755
likelihood: 0.4337899543378995
Total deposit: 5289
Evidence: 0.4738398136534671
Prosterior: 0.5208924182265078

In [ ]:
 bank_data["education"]

0        secondary
1        secondary
2        secondary
3        secondary
4         tertiary
           ...
11158    secondary
11159    secondary
11160    secondary
11161    secondary
11162          NaN
Name: education, Length: 11163, dtype: object

In [ ]:
total_count = bank_data.count()[0]

df_secondary =bank_data[ bank_data["education"] == "secondary" ]
total_secondary_count = df_secondary.count()[0]
print("Total secondary:",total_secondary_count)
prior = total_secondary_count/total_count 
print("prior",prior )

df_secondary_non_deposit =bank_data [ (bank_data["education"] == "secondary") & (bank_data["deposit"] == 'no') ]
secondary_non_deposit_count = df_secondary_non_deposit.count()[0]
print("Total secondary_non_deposit:",secondary_non_deposit_count)
likelihood = secondary_non_deposit_count / (total_secondary_count)
print("likelihood:" ,likelihood) 

df_non_deposit =bank_data[bank_data["deposit"] == "no"]
total_non_deposit_count = df_non_deposit.count()[0]
print("Total non deposit:",total_non_deposit_count)
Evidence =  total_non_deposit_count/total_count
print("Evidence:",Evidence )

Prosterior =  (likelihood*prior)/Evidence
print("Prosterior:",Prosterior )

Total secondary: 5476
prior 0.4905930836767604
Total secondary_non_deposit: 3026
likelihood: 0.5525931336742148
Total non deposit: 5873
Evidence: 0.5261601863465328
Prosterior: 0.5152392303762984

In [ ]:
total_count = bank_data.count()[0]

df_secondary =bank_data[ bank_data["education"] == "secondary" ]
total_secondary_count = df_secondary.count()[0]
print("Total secondary:",total_secondary_count)
prior = total_secondary_count/total_count 
print("prior",prior )

df_secondary_deposit =bank_data [ (bank_data["education"] == "secondary") & (bank_data["deposit"] == 'yes') ]
secondary_deposit_count = df_secondary_deposit.count()[0]
print("Total secondary_deposit:",secondary_deposit_count)
likelihood = secondary_deposit_count / (total_secondary_count)
print("likelihood:" ,likelihood) 

df_deposit =bank_data[bank_data["deposit"] == "yes"]
total_deposit_count = df_deposit.count()[0]
print("Total deposit:",total_deposit_count)
Evidence =  total_deposit_count/total_count
print("Evidence:",Evidence )

Prosterior =  (likelihood*prior)/Evidence
print("Prosterior:",Prosterior )

# Calculate accuracy
accuracy = (total_secondary_count + total_deposit_count) / total_count
accuracy_percentage = accuracy * 100
print("Accuracy: %.2f%%" % accuracy_percentage)

Total secondary: 5476
prior 0.4905930836767604
Total secondary_deposit: 2450
likelihood: 0.44740686632578525
Total deposit: 5289
Evidence: 0.4738398136534671
Prosterior: 0.463225562488183
Accuracy: 96.44%

In [ ]:
from sklearn.preprocessing import StandardScaler

# Copying original dataframe
df_bank_ready = bank_data.copy()

scaler = StandardScaler()
num_cols = ['age', 'balance', 'day', 'campaign', 'pdays', 'previous']
df_bank_ready[num_cols] = scaler.fit_transform(df_bank_ready[num_cols])

df_bank_ready.head()

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,deposit
0,1.491505,admin.,married,secondary,no,0.252525,yes,no,unknown,-1.265746,may,1042.0,-0.554168,-0.481184,-0.36326,unknown,yes
1,1.239676,admin.,married,secondary,no,-0.459974,no,no,unknown,-1.265746,may,1467.0,-0.554168,-0.481184,-0.36326,unknown,yes
2,-0.019470,technician,married,secondary,no,-0.080160,yes,no,unknown,-1.265746,may,1389.0,-0.554168,-0.481184,-0.36326,unknown,yes
3,1.155733,services,married,secondary,no,0.293762,yes,no,unknown,-1.265746,may,579.0,-0.554168,-0.481184,-0.36326,unknown,yes
4,1.071790,admin.,married,tertiary,no,-0.416876,no,no,unknown,-1.265746,may,673.0,-0.186785,-0.481184,-0.36326,unknown,yes

In [ ]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse=False)
cat_cols = ['job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'poutcome']

# Encode Categorical Data
df_encoded = pd.DataFrame(encoder.fit_transform(df_bank_ready[cat_cols]))
df_encoded.columns = encoder.get_feature_names_out(cat_cols)

# Replace Categorical Data with Encoded Data
df_bank_ready = df_bank_ready.drop(cat_cols, axis=1)
df_bank_ready = pd.concat([df_encoded, df_bank_ready], axis=1)

# Encode target value
df_bank_ready['deposit'] = df_bank_ready['deposit'].apply(lambda x: 1 if x == 'yes' else 0)

print('Shape of dataframe:', df_bank_ready.shape)
df_bank_ready.head()

Shape of dataframe: (11163, 61)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,...,poutcome_unknown,poutcome_nan,age,balance,day,duration,campaign,pdays,previous,deposit
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.491505,0.252525,-1.265746,1042.0,-0.554168,-0.481184,-0.36326,1
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.239676,-0.459974,-1.265746,1467.0,-0.554168,-0.481184,-0.36326,1
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,-0.019470,-0.080160,-1.265746,1389.0,-0.554168,-0.481184,-0.36326,1
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,1.155733,0.293762,-1.265746,579.0,-0.554168,-0.481184,-0.36326,1
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.071790,-0.416876,-1.265746,673.0,-0.186785,-0.481184,-0.36326,1

In [ ]:
# Select Features
feature = df_bank_ready.drop('deposit', axis=1)

# Select Target
target = df_bank_ready['deposit']

# Set Training and Testing Data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(feature , target, 
                                                    shuffle = True, 
                                                    test_size=0.2, 
                                                    random_state=1)

# Show the Training and Testing Data
print('Shape of training feature:', X_train.shape)
print('Shape of testing feature:', X_test.shape)
print('Shape of training label:', y_train.shape)
print('Shape of training label:', y_test.shape)

Shape of training feature: (8930, 60)
Shape of testing feature: (2233, 60)
Shape of training label: (8930,)
Shape of training label: (2233,)

In [ ]:
from sklearn.naive_bayes import GaussianNB
from sklearn.impute import SimpleImputer

# Handle missing values in X_train
imputer = SimpleImputer(strategy='mean')  
X_train_imputed = imputer.fit_transform(X_train)

# Building Naive Bayes model
nb = GaussianNB()
nb.fit(X_train_imputed, y_train)

GaussianNB()

In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score

def evaluate_model(model, X_test, y_test):
    predictions = model.predict(X_test)
    accuracy = model.score(X_test, y_test)
    precision = precision_score(y_test, predictions)
    recall = recall_score(y_test, predictions)
    f1 = f1_score(y_test, predictions)

    evaluation = {
        'acc': accuracy,
        'prec': precision,
        'rec': recall,
        'f1': f1
    }

    return evaluation


# Evaluate Model
nb_eval = evaluate_model(nb, X_test.values, y_test.values)  # Convert X_test and y_test to arrays

# Print result
print('Accuracy: %.2f' % (nb_eval['acc']*100),"%")
print('Precision: %.2f' % (nb_eval['prec']*100),"%")
print('Recall: %.2f' % (nb_eval['rec']*100),"%")
print('F1 Score: %.2f' % (nb_eval['f1']*100),"%")

Accuracy: 72.86 %
Precision: 70.99 %
Recall: 73.51 %
F1 Score: 72.23 %

**Perceptron**

In [ ]:
import numpy as np

# Define the perceptron class
class Perceptron:
    def __init__(self, num_features, learning_rate=0.1, max_epochs=100):
        self.weights = np.zeros(num_features)  # Initialize weights to zero
        self.learning_rate = learning_rate
        self.max_epochs = max_epochs

    def train(self, X, y):
        epoch = 0
        while epoch < self.max_epochs:
            error_count = 0
            for i in range(len(X)):
                y_pred = self.predict(X[i])
                error = y[i] - y_pred
                if error != 0:
                    self.weights += self.learning_rate * error * X[i]
                    error_count += 1
            if error_count == 0:
                break
            epoch += 1

    def predict(self, x):
        activation = np.dot(self.weights, x)
        return 1 if activation >= 0 else 0


# Create the bank marketing dataset
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([0, 0, 0, 1])

# Create and train the perceptron model
perceptron = Perceptron(num_features=2)
perceptron.train(X, y)

# Test the model on new data
test_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
for data in test_data:
    prediction = perceptron.predict(data)
    print(f"Input: {data}, Prediction: {prediction}")

Input: [0 0], Prediction: 1
Input: [0 1], Prediction: 1
Input: [1 0], Prediction: 1
Input: [1 1], Prediction: 1

In [ ]:
Xs = [[0, 0], [0, 1], [1, 0], [1,1]]
Ys = [0, 0, 0, 1]
TD = [[([0, 0], 0), ([0, 1],0)],[ ([1, 0],0),  ([1,1], 1)]]
eta = 0.05

In [ ]:
def f(X, W):
  return W[0] + W[1]*X[0] + W[2]*X[1]

def A(x):
  if x>0:
    return 1
  else:
    return 0

def Y(X, W):
  return A(f(X,W))

In [ ]:
w = [56, 34, 73]

In [ ]:
Pred = []
for X in Xs:
  ret = Y(X, w)
  Pred.append(ret)
print(Pred)

[1, 1, 1, 1]

In [ ]:
def MSE(Pred, T):
  err = 0
  for i in range(len(T)):
    err = err + (Pred[i] - T[i])*(Pred[i] - T[i])
  return err/len(T)

In [ ]:
MSE(Pred, Ys)

0.75

In [ ]:
def back_prop(TD, w, grad = True):
  Pred = []
  Ts = []
  for batch in TD:
    delw = [0, 0, 0]
    for tt in batch:
      X, T = tt
      P = Y(X, w)
      Pred.append(P)
      Ts.append(T)
      delw[0] = delw[0] + eta * (P-T)*1
      delw[1] = delw[1] + eta * (P-T)*X[0]
      delw[2] = delw[2] + eta * (P-T)*X[1]
    if grad == True:
      w[0] = w[0] - delw[0]
      w[1] = w[1] - delw[1]
      w[2] = w[2] - delw[2]
  return MSE(Pred, Ts)

In [ ]:
def train( TD, w ):
  mse = back_prop(TD, w, grad=False)
  epoch = 0;
  print("Epoch {}: Err={} and weight = {}".format(epoch,mse, w))
  while mse != 0:
    epoch = epoch + 1
    mse = back_prop(TD, w, grad=True)
    print("Epoch {}: Err={} and weight = {}".format(epoch,mse, w))

In [ ]:
train(TD, w)

Epoch 0: Err=0.75 and weight = [56, 34, 73]
Epoch 1: Err=0.75 and weight = [55.85, 33.95, 72.95]
Epoch 2: Err=0.75 and weight = [55.7, 33.900000000000006, 72.9]
Epoch 3: Err=0.75 and weight = [55.550000000000004, 33.85000000000001, 72.85000000000001]
Epoch 4: Err=0.75 and weight = [55.400000000000006, 33.80000000000001, 72.80000000000001]
Epoch 5: Err=0.75 and weight = [55.25000000000001, 33.750000000000014, 72.75000000000001]
Epoch 6: Err=0.75 and weight = [55.10000000000001, 33.70000000000002, 72.70000000000002]
Epoch 7: Err=0.75 and weight = [54.95000000000001, 33.65000000000002, 72.65000000000002]
Epoch 8: Err=0.75 and weight = [54.80000000000001, 33.60000000000002, 72.60000000000002]
Epoch 9: Err=0.75 and weight = [54.65000000000001, 33.550000000000026, 72.55000000000003]
Epoch 10: Err=0.75 and weight = [54.500000000000014, 33.50000000000003, 72.50000000000003]
Epoch 11: Err=0.75 and weight = [54.350000000000016, 33.45000000000003, 72.45000000000003]
Epoch 12: Err=0.75 and weight = [54.20000000000002, 33.400000000000034, 72.40000000000003]
Epoch 13: Err=0.75 and weight = [54.05000000000002, 33.35000000000004, 72.35000000000004]
Epoch 14: Err=0.75 and weight = [53.90000000000002, 33.30000000000004, 72.30000000000004]
Epoch 15: Err=0.75 and weight = [53.75000000000002, 33.25000000000004, 72.25000000000004]
Epoch 16: Err=0.75 and weight = [53.60000000000002, 33.200000000000045, 72.20000000000005]
Epoch 17: Err=0.75 and weight = [53.450000000000024, 33.15000000000005, 72.15000000000005]
Epoch 18: Err=0.75 and weight = [53.300000000000026, 33.10000000000005, 72.10000000000005]
Epoch 19: Err=0.75 and weight = [53.15000000000003, 33.050000000000054, 72.05000000000005]
Epoch 20: Err=0.75 and weight = [53.00000000000003, 33.00000000000006, 72.00000000000006]
Epoch 21: Err=0.75 and weight = [52.85000000000003, 32.95000000000006, 71.95000000000006]
Epoch 22: Err=0.75 and weight = [52.70000000000003, 32.90000000000006, 71.90000000000006]
Epoch 23: Err=0.75 and weight = [52.55000000000003, 32.850000000000065, 71.85000000000007]
Epoch 24: Err=0.75 and weight = [52.400000000000034, 32.80000000000007, 71.80000000000007]
Epoch 25: Err=0.75 and weight = [52.250000000000036, 32.75000000000007, 71.75000000000007]
Epoch 26: Err=0.75 and weight = [52.10000000000004, 32.700000000000074, 71.70000000000007]
Epoch 27: Err=0.75 and weight = [51.95000000000004, 32.65000000000008, 71.65000000000008]
Epoch 28: Err=0.75 and weight = [51.80000000000004, 32.60000000000008, 71.60000000000008]
Epoch 29: Err=0.75 and weight = [51.65000000000004, 32.55000000000008, 71.55000000000008]
Epoch 30: Err=0.75 and weight = [51.50000000000004, 32.500000000000085, 71.50000000000009]
Epoch 31: Err=0.75 and weight = [51.350000000000044, 32.45000000000009, 71.45000000000009]
Epoch 32: Err=0.75 and weight = [51.200000000000045, 32.40000000000009, 71.40000000000009]
Epoch 33: Err=0.75 and weight = [51.05000000000005, 32.350000000000094, 71.3500000000001]
Epoch 34: Err=0.75 and weight = [50.90000000000005, 32.3000000000001, 71.3000000000001]
Epoch 35: Err=0.75 and weight = [50.75000000000005, 32.2500000000001, 71.2500000000001]
Epoch 36: Err=0.75 and weight = [50.60000000000005, 32.2000000000001, 71.2000000000001]
Epoch 37: Err=0.75 and weight = [50.45000000000005, 32.150000000000105, 71.1500000000001]
Epoch 38: Err=0.75 and weight = [50.300000000000054, 32.10000000000011, 71.10000000000011]
Epoch 39: Err=0.75 and weight = [50.150000000000055, 32.05000000000011, 71.05000000000011]
Epoch 40: Err=0.75 and weight = [50.00000000000006, 32.000000000000114, 71.00000000000011]
Epoch 41: Err=0.75 and weight = [49.85000000000006, 31.950000000000113, 70.95000000000012]
Epoch 42: Err=0.75 and weight = [49.70000000000006, 31.900000000000112, 70.90000000000012]
Epoch 43: Err=0.75 and weight = [49.55000000000006, 31.85000000000011, 70.85000000000012]
Epoch 44: Err=0.75 and weight = [49.40000000000006, 31.80000000000011, 70.80000000000013]
Epoch 45: Err=0.75 and weight = [49.250000000000064, 31.75000000000011, 70.75000000000013]
Epoch 46: Err=0.75 and weight = [49.100000000000065, 31.70000000000011, 70.70000000000013]
Epoch 47: Err=0.75 and weight = [48.95000000000007, 31.65000000000011, 70.65000000000013]
Epoch 48: Err=0.75 and weight = [48.80000000000007, 31.600000000000108, 70.60000000000014]
Epoch 49: Err=0.75 and weight = [48.65000000000007, 31.550000000000107, 70.55000000000014]
Epoch 50: Err=0.75 and weight = [48.50000000000007, 31.500000000000107, 70.50000000000014]
Epoch 51: Err=0.75 and weight = [48.35000000000007, 31.450000000000106, 70.45000000000014]
Epoch 52: Err=0.75 and weight = [48.200000000000074, 31.400000000000105, 70.40000000000015]
Epoch 53: Err=0.75 and weight = [48.050000000000075, 31.350000000000104, 70.35000000000015]
Epoch 54: Err=0.75 and weight = [47.90000000000008, 31.300000000000104, 70.30000000000015]
Epoch 55: Err=0.75 and weight = [47.75000000000008, 31.250000000000103, 70.25000000000016]
Epoch 56: Err=0.75 and weight = [47.60000000000008, 31.200000000000102, 70.20000000000016]
Epoch 57: Err=0.75 and weight = [47.45000000000008, 31.1500000000001, 70.15000000000016]
Epoch 58: Err=0.75 and weight = [47.30000000000008, 31.1000000000001, 70.10000000000016]
Epoch 59: Err=0.75 and weight = [47.150000000000084, 31.0500000000001, 70.05000000000017]
Epoch 60: Err=0.75 and weight = [47.000000000000085, 31.0000000000001, 70.00000000000017]
Epoch 61: Err=0.75 and weight = [46.85000000000009, 30.9500000000001, 69.95000000000017]
Epoch 62: Err=0.75 and weight = [46.70000000000009, 30.900000000000098, 69.90000000000018]
Epoch 63: Err=0.75 and weight = [46.55000000000009, 30.850000000000097, 69.85000000000018]
Epoch 64: Err=0.75 and weight = [46.40000000000009, 30.800000000000097, 69.80000000000018]
Epoch 65: Err=0.75 and weight = [46.25000000000009, 30.750000000000096, 69.75000000000018]
Epoch 66: Err=0.75 and weight = [46.100000000000094, 30.700000000000095, 69.70000000000019]
Epoch 67: Err=0.75 and weight = [45.950000000000095, 30.650000000000095, 69.65000000000019]
Epoch 68: Err=0.75 and weight = [45.8000000000001, 30.600000000000094, 69.6000000000002]
Epoch 69: Err=0.75 and weight = [45.6500000000001, 30.550000000000093, 69.5500000000002]
Epoch 70: Err=0.75 and weight = [45.5000000000001, 30.500000000000092, 69.5000000000002]
Epoch 71: Err=0.75 and weight = [45.3500000000001, 30.45000000000009, 69.4500000000002]
Epoch 72: Err=0.75 and weight = [45.2000000000001, 30.40000000000009, 69.4000000000002]
Epoch 73: Err=0.75 and weight = [45.050000000000104, 30.35000000000009, 69.35000000000021]
Epoch 74: Err=0.75 and weight = [44.900000000000105, 30.30000000000009, 69.30000000000021]
Epoch 75: Err=0.75 and weight = [44.75000000000011, 30.25000000000009, 69.25000000000021]
Epoch 76: Err=0.75 and weight = [44.60000000000011, 30.200000000000088, 69.20000000000022]
Epoch 77: Err=0.75 and weight = [44.45000000000011, 30.150000000000087, 69.15000000000022]
Epoch 78: Err=0.75 and weight = [44.30000000000011, 30.100000000000087, 69.10000000000022]
Epoch 79: Err=0.75 and weight = [44.15000000000011, 30.050000000000086, 69.05000000000022]
Epoch 80: Err=0.75 and weight = [44.000000000000114, 30.000000000000085, 69.00000000000023]
Epoch 81: Err=0.75 and weight = [43.850000000000115, 29.950000000000085, 68.95000000000023]
Epoch 82: Err=0.75 and weight = [43.70000000000012, 29.900000000000084, 68.90000000000023]
Epoch 83: Err=0.75 and weight = [43.55000000000012, 29.850000000000083, 68.85000000000024]
Epoch 84: Err=0.75 and weight = [43.40000000000012, 29.800000000000082, 68.80000000000024]
Epoch 85: Err=0.75 and weight = [43.25000000000012, 29.75000000000008, 68.75000000000024]
Epoch 86: Err=0.75 and weight = [43.10000000000012, 29.70000000000008, 68.70000000000024]
Epoch 87: Err=0.75 and weight = [42.950000000000124, 29.65000000000008, 68.65000000000025]
Epoch 88: Err=0.75 and weight = [42.800000000000125, 29.60000000000008, 68.60000000000025]
Epoch 89: Err=0.75 and weight = [42.65000000000013, 29.55000000000008, 68.55000000000025]
Epoch 90: Err=0.75 and weight = [42.50000000000013, 29.500000000000078, 68.50000000000026]
Epoch 91: Err=0.75 and weight = [42.35000000000013, 29.450000000000077, 68.45000000000026]
Epoch 92: Err=0.75 and weight = [42.20000000000013, 29.400000000000077, 68.40000000000026]
Epoch 93: Err=0.75 and weight = [42.05000000000013, 29.350000000000076, 68.35000000000026]
Epoch 94: Err=0.75 and weight = [41.900000000000134, 29.300000000000075, 68.30000000000027]
Epoch 95: Err=0.75 and weight = [41.750000000000135, 29.250000000000075, 68.25000000000027]
Epoch 96: Err=0.75 and weight = [41.600000000000136, 29.200000000000074, 68.20000000000027]
Epoch 97: Err=0.75 and weight = [41.45000000000014, 29.150000000000073, 68.15000000000028]
Epoch 98: Err=0.75 and weight = [41.30000000000014, 29.100000000000072, 68.10000000000028]
Epoch 99: Err=0.75 and weight = [41.15000000000014, 29.05000000000007, 68.05000000000028]
Epoch 100: Err=0.75 and weight = [41.00000000000014, 29.00000000000007, 68.00000000000028]
Epoch 101: Err=0.75 and weight = [40.85000000000014, 28.95000000000007, 67.95000000000029]
Epoch 102: Err=0.75 and weight = [40.700000000000145, 28.90000000000007, 67.90000000000029]
Epoch 103: Err=0.75 and weight = [40.550000000000146, 28.85000000000007, 67.85000000000029]
Epoch 104: Err=0.75 and weight = [40.40000000000015, 28.800000000000068, 67.8000000000003]
Epoch 105: Err=0.75 and weight = [40.25000000000015, 28.750000000000068, 67.7500000000003]
Epoch 106: Err=0.75 and weight = [40.10000000000015, 28.700000000000067, 67.7000000000003]
Epoch 107: Err=0.75 and weight = [39.95000000000015, 28.650000000000066, 67.6500000000003]
Epoch 108: Err=0.75 and weight = [39.80000000000015, 28.600000000000065, 67.6000000000003]
Epoch 109: Err=0.75 and weight = [39.650000000000155, 28.550000000000065, 67.55000000000031]
Epoch 110: Err=0.75 and weight = [39.500000000000156, 28.500000000000064, 67.50000000000031]
Epoch 111: Err=0.75 and weight = [39.35000000000016, 28.450000000000063, 67.45000000000032]
Epoch 112: Err=0.75 and weight = [39.20000000000016, 28.400000000000063, 67.40000000000032]
Epoch 113: Err=0.75 and weight = [39.05000000000016, 28.350000000000062, 67.35000000000032]
Epoch 114: Err=0.75 and weight = [38.90000000000016, 28.30000000000006, 67.30000000000032]
Epoch 115: Err=0.75 and weight = [38.75000000000016, 28.25000000000006, 67.25000000000033]
Epoch 116: Err=0.75 and weight = [38.600000000000165, 28.20000000000006, 67.20000000000033]
Epoch 117: Err=0.75 and weight = [38.450000000000166, 28.15000000000006, 67.15000000000033]
Epoch 118: Err=0.75 and weight = [38.30000000000017, 28.10000000000006, 67.10000000000034]
Epoch 119: Err=0.75 and weight = [38.15000000000017, 28.050000000000058, 67.05000000000034]
Epoch 120: Err=0.75 and weight = [38.00000000000017, 28.000000000000057, 67.00000000000034]
Epoch 121: Err=0.75 and weight = [37.85000000000017, 27.950000000000056, 66.95000000000034]
Epoch 122: Err=0.75 and weight = [37.70000000000017, 27.900000000000055, 66.90000000000035]
Epoch 123: Err=0.75 and weight = [37.550000000000175, 27.850000000000055, 66.85000000000035]
Epoch 124: Err=0.75 and weight = [37.400000000000176, 27.800000000000054, 66.80000000000035]
Epoch 125: Err=0.75 and weight = [37.25000000000018, 27.750000000000053, 66.75000000000036]
Epoch 126: Err=0.75 and weight = [37.10000000000018, 27.700000000000053, 66.70000000000036]
Epoch 127: Err=0.75 and weight = [36.95000000000018, 27.650000000000052, 66.65000000000036]
Epoch 128: Err=0.75 and weight = [36.80000000000018, 27.60000000000005, 66.60000000000036]
Epoch 129: Err=0.75 and weight = [36.65000000000018, 27.55000000000005, 66.55000000000037]
Epoch 130: Err=0.75 and weight = [36.500000000000185, 27.50000000000005, 66.50000000000037]
Epoch 131: Err=0.75 and weight = [36.350000000000186, 27.45000000000005, 66.45000000000037]
Epoch 132: Err=0.75 and weight = [36.20000000000019, 27.40000000000005, 66.40000000000038]
Epoch 133: Err=0.75 and weight = [36.05000000000019, 27.350000000000048, 66.35000000000038]
Epoch 134: Err=0.75 and weight = [35.90000000000019, 27.300000000000047, 66.30000000000038]
Epoch 135: Err=0.75 and weight = [35.75000000000019, 27.250000000000046, 66.25000000000038]
Epoch 136: Err=0.75 and weight = [35.60000000000019, 27.200000000000045, 66.20000000000039]
Epoch 137: Err=0.75 and weight = [35.450000000000195, 27.150000000000045, 66.15000000000039]
Epoch 138: Err=0.75 and weight = [35.300000000000196, 27.100000000000044, 66.10000000000039]
Epoch 139: Err=0.75 and weight = [35.1500000000002, 27.050000000000043, 66.0500000000004]
Epoch 140: Err=0.75 and weight = [35.0000000000002, 27.000000000000043, 66.0000000000004]
Epoch 141: Err=0.75 and weight = [34.8500000000002, 26.950000000000042, 65.9500000000004]
Epoch 142: Err=0.75 and weight = [34.7000000000002, 26.90000000000004, 65.9000000000004]
Epoch 143: Err=0.75 and weight = [34.5500000000002, 26.85000000000004, 65.8500000000004]
Epoch 144: Err=0.75 and weight = [34.400000000000205, 26.80000000000004, 65.80000000000041]
Epoch 145: Err=0.75 and weight = [34.250000000000206, 26.75000000000004, 65.75000000000041]
Epoch 146: Err=0.75 and weight = [34.10000000000021, 26.70000000000004, 65.70000000000041]
Epoch 147: Err=0.75 and weight = [33.95000000000021, 26.650000000000038, 65.65000000000042]
Epoch 148: Err=0.75 and weight = [33.80000000000021, 26.600000000000037, 65.60000000000042]
Epoch 149: Err=0.75 and weight = [33.65000000000021, 26.550000000000036, 65.55000000000042]
Epoch 150: Err=0.75 and weight = [33.50000000000021, 26.500000000000036, 65.50000000000043]
Epoch 151: Err=0.75 and weight = [33.350000000000215, 26.450000000000035, 65.45000000000043]
Epoch 152: Err=0.75 and weight = [33.200000000000216, 26.400000000000034, 65.40000000000043]
Epoch 153: Err=0.75 and weight = [33.05000000000022, 26.350000000000033, 65.35000000000043]
Epoch 154: Err=0.75 and weight = [32.90000000000022, 26.300000000000033, 65.30000000000044]
Epoch 155: Err=0.75 and weight = [32.75000000000022, 26.250000000000032, 65.25000000000044]
Epoch 156: Err=0.75 and weight = [32.60000000000022, 26.20000000000003, 65.20000000000044]
Epoch 157: Err=0.75 and weight = [32.45000000000022, 26.15000000000003, 65.15000000000045]
Epoch 158: Err=0.75 and weight = [32.300000000000225, 26.10000000000003, 65.10000000000045]
Epoch 159: Err=0.75 and weight = [32.150000000000226, 26.05000000000003, 65.05000000000045]
Epoch 160: Err=0.75 and weight = [32.00000000000023, 26.00000000000003, 65.00000000000045]
Epoch 161: Err=0.75 and weight = [31.850000000000225, 25.950000000000028, 64.95000000000046]
Epoch 162: Err=0.75 and weight = [31.700000000000223, 25.900000000000027, 64.90000000000046]
Epoch 163: Err=0.75 and weight = [31.55000000000022, 25.850000000000026, 64.85000000000046]
Epoch 164: Err=0.75 and weight = [31.40000000000022, 25.800000000000026, 64.80000000000047]
Epoch 165: Err=0.75 and weight = [31.250000000000217, 25.750000000000025, 64.75000000000047]
Epoch 166: Err=0.75 and weight = [31.100000000000215, 25.700000000000024, 64.70000000000047]
Epoch 167: Err=0.75 and weight = [30.950000000000212, 25.650000000000023, 64.65000000000047]
Epoch 168: Err=0.75 and weight = [30.80000000000021, 25.600000000000023, 64.60000000000048]
Epoch 169: Err=0.75 and weight = [30.650000000000208, 25.550000000000022, 64.55000000000048]
Epoch 170: Err=0.75 and weight = [30.500000000000206, 25.50000000000002, 64.50000000000048]
Epoch 171: Err=0.75 and weight = [30.350000000000204, 25.45000000000002, 64.45000000000049]
Epoch 172: Err=0.75 and weight = [30.200000000000202, 25.40000000000002, 64.40000000000049]
Epoch 173: Err=0.75 and weight = [30.0500000000002, 25.35000000000002, 64.35000000000049]
Epoch 174: Err=0.75 and weight = [29.900000000000198, 25.30000000000002, 64.3000000000005]
Epoch 175: Err=0.75 and weight = [29.750000000000195, 25.250000000000018, 64.2500000000005]
Epoch 176: Err=0.75 and weight = [29.600000000000193, 25.200000000000017, 64.2000000000005]
Epoch 177: Err=0.75 and weight = [29.45000000000019, 25.150000000000016, 64.1500000000005]
Epoch 178: Err=0.75 and weight = [29.30000000000019, 25.100000000000016, 64.1000000000005]
Epoch 179: Err=0.75 and weight = [29.150000000000187, 25.050000000000015, 64.05000000000051]
Epoch 180: Err=0.75 and weight = [29.000000000000185, 25.000000000000014, 64.00000000000051]
Epoch 181: Err=0.75 and weight = [28.850000000000183, 24.950000000000014, 63.950000000000514]
Epoch 182: Err=0.75 and weight = [28.70000000000018, 24.900000000000013, 63.90000000000052]
Epoch 183: Err=0.75 and weight = [28.55000000000018, 24.850000000000012, 63.85000000000052]
Epoch 184: Err=0.75 and weight = [28.400000000000176, 24.80000000000001, 63.80000000000052]
Epoch 185: Err=0.75 and weight = [28.250000000000174, 24.75000000000001, 63.750000000000526]
Epoch 186: Err=0.75 and weight = [28.100000000000172, 24.70000000000001, 63.70000000000053]
Epoch 187: Err=0.75 and weight = [27.95000000000017, 24.65000000000001, 63.65000000000053]
Epoch 188: Err=0.75 and weight = [27.800000000000168, 24.60000000000001, 63.600000000000534]
Epoch 189: Err=0.75 and weight = [27.650000000000166, 24.550000000000008, 63.55000000000054]
Epoch 190: Err=0.75 and weight = [27.500000000000163, 24.500000000000007, 63.50000000000054]
Epoch 191: Err=0.75 and weight = [27.35000000000016, 24.450000000000006, 63.45000000000054]
Epoch 192: Err=0.75 and weight = [27.20000000000016, 24.400000000000006, 63.400000000000546]
Epoch 193: Err=0.75 and weight = [27.050000000000157, 24.350000000000005, 63.35000000000055]
Epoch 194: Err=0.75 and weight = [26.900000000000155, 24.300000000000004, 63.30000000000055]
Epoch 195: Err=0.75 and weight = [26.750000000000153, 24.250000000000004, 63.250000000000554]
Epoch 196: Err=0.75 and weight = [26.60000000000015, 24.200000000000003, 63.20000000000056]
Epoch 197: Err=0.75 and weight = [26.45000000000015, 24.150000000000002, 63.15000000000056]
Epoch 198: Err=0.75 and weight = [26.300000000000146, 24.1, 63.10000000000056]
Epoch 199: Err=0.75 and weight = [26.150000000000144, 24.05, 63.050000000000566]
Epoch 200: Err=0.75 and weight = [26.000000000000142, 24.0, 63.00000000000057]
Epoch 201: Err=0.75 and weight = [25.85000000000014, 23.95, 62.95000000000057]
Epoch 202: Err=0.75 and weight = [25.700000000000138, 23.9, 62.900000000000574]
Epoch 203: Err=0.75 and weight = [25.550000000000136, 23.849999999999998, 62.85000000000058]
Epoch 204: Err=0.75 and weight = [25.400000000000134, 23.799999999999997, 62.80000000000058]
Epoch 205: Err=0.75 and weight = [25.25000000000013, 23.749999999999996, 62.75000000000058]
Epoch 206: Err=0.75 and weight = [25.10000000000013, 23.699999999999996, 62.700000000000585]
Epoch 207: Err=0.75 and weight = [24.950000000000127, 23.649999999999995, 62.65000000000059]
Epoch 208: Err=0.75 and weight = [24.800000000000125, 23.599999999999994, 62.60000000000059]
Epoch 209: Err=0.75 and weight = [24.650000000000123, 23.549999999999994, 62.550000000000594]
Epoch 210: Err=0.75 and weight = [24.50000000000012, 23.499999999999993, 62.5000000000006]
Epoch 211: Err=0.75 and weight = [24.35000000000012, 23.449999999999992, 62.4500000000006]
Epoch 212: Err=0.75 and weight = [24.200000000000117, 23.39999999999999, 62.4000000000006]
Epoch 213: Err=0.75 and weight = [24.050000000000114, 23.34999999999999, 62.350000000000605]
Epoch 214: Err=0.75 and weight = [23.900000000000112, 23.29999999999999, 62.30000000000061]
Epoch 215: Err=0.75 and weight = [23.75000000000011, 23.24999999999999, 62.25000000000061]
Epoch 216: Err=0.75 and weight = [23.600000000000108, 23.19999999999999, 62.200000000000614]
Epoch 217: Err=0.75 and weight = [23.450000000000106, 23.149999999999988, 62.15000000000062]
Epoch 218: Err=0.75 and weight = [23.300000000000104, 23.099999999999987, 62.10000000000062]
Epoch 219: Err=0.75 and weight = [23.1500000000001, 23.049999999999986, 62.05000000000062]

In [ ]:
print(w)

[-29.75000000000029, 10.249999999999805, 29.700000000002298]